version: "3.8"



services:
  mongodb:
    image: mongo:latest
    container_name: nullpointer_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: userdb 
    volumes:
      - /docker/nullpointermongodb:/data/db
    ports:
      - "27017:27017"

